#!/bin/bash

set -e


function usage() {
    echo ""
    echo "git clear-compiled [--dry-run]"
}

# actually parse the options and do stuff
while [[ $1 = -?* ]]; do
    case $1 in
        -h|--help)
            usage
            exit 0
            ;;
        -d|--dry-run)
            echo "Dry run."
            find . -type d \( -name bin -o -name obj \) -exec echo Would delete: {} \;
            exit 0
            ;;
        *) ;;
    esac

shift
done

echo "Deleting **/bin/ and **/obj/ directories:"
find . -type d \( -name bin -o -name obj \) -prune -exec rm -rf {} \; -exec echo deleted: {} \;
echo "Done"